# panos shared log settings configuration snippets

name: panos_ngfw_shared_log_settings_10_0
label: PAN_OS NGFW Shared Log Settings
description: |-
    reference shared log settings configuration snippets
type: panos
labels:
    collection:
      - PAN-OS

variables:

  - name: SYSLOG_SERVER
    description: syslog server ip address
    default: 192.0.2.2
    type_hint: text

snippets:

-   name: ironskillet_shared_log_settings_sample_syslog_profile
    xpath: /config/shared/log-settings
    element: |-
      <syslog>
        <entry name="Sample_Syslog_Profile">
          <server>
            <entry name="Sample_Syslog">
              <transport>UDP</transport>
              <port>514</port>
              <format>BSD</format>
              <server>{{ SYSLOG_SERVER }}</server>
              <facility>LOG_USER</facility>
            </entry>
          </server>
        </entry>
      </syslog>

-   name: ironskillet_shared_log_settings_syslog_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <system>
        <match-list>
          <entry name="System_Log_Forwarding">
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
        </match-list>
      </system>

-   name: ironskillet_shared_log_settings_log_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <config>
        <match-list>
          <entry name="Configuration_Log_Forwarding">
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
        </match-list>
      </config>

-   name: ironskillet_shared_log_settings_userid_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <userid>
        <match-list>
          <entry name="User-ID_Log_Forwarding">
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
        </match-list>
      </userid>

-   name: ironskillet_shared_log_settings_hip_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <hipmatch>
        <match-list>
          <entry name="HIP_Log_Forwarding">
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
          </entry>
        </match-list>
      </hipmatch>

-   name: ironskillet_shared_log_settings_gp_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <globalprotect>
        <match-list>
          <entry name="GP_Log_Forwarding">
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
          </entry>
        </match-list>
      </globalprotect>

-   name: ironskillet_shared_log_settings_ip_tag_forwarding
    xpath: /config/shared/log-settings
    element: |-
      <iptag>
        <match-list>
          <entry name="IP-Tag_Log_Forwarding">
            <send-syslog>
              <member>Sample_Syslog_Profile</member>
            </send-syslog>
            <filter>All Logs</filter>
            <send-to-panorama>no</send-to-panorama>
          </entry>
        </match-list>
      </iptag>