name: validate-IronSkillet-v10_0-panos-bae945bc-c667-4e56-a3fc-73bbb5afbe0g
label: IronSkillet - check NGFW config for updated v10.0 elements

description: |
  Check NGFW for new items updated in IronSkillet v10.x skillet

type: pan_validation
labels:
  collection:
    - IronSkillet
    - Validation

variables:

snippets:

  - name: rules
    cmd: parse
    variable: config
    outputs:
      # used to check WF update interval
      - name: wf_update
        capture_object: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/wildfire
      - name: as_profiles_outbound_dns
        capture_object: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/spyware/entry[@name='Outbound-AS']/botnet-domains/lists

      # check if Outbound-URL profile exists
      - name: url_outbound
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering
          /entry[@name='Outbound-URL']/@name
      # check that dynamic class is part of url filtering config
      - name: url_dynclass_entries
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering
          /entry[@name='Outbound-URL']/mlav-engine-urlbased-enabled/entry/@name
      # list of dynamic classification options set to block
      - name: url_dynclass_block
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering
          /entry[@name='Outbound-URL']/mlav-engine-urlbased-enabled/entry/mlav-policy-action[text()='block']/../@name
      # list of dynamic classification options not set to block
      - name: url_dynclass_not_block
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering
          /entry[@name='Outbound-URL']/mlav-engine-urlbased-enabled/entry/@name
        filter_items: item not in url_dynclass_block
      # list with the profile name if hacking is alert
      - name: url_profiles_alert_hacking
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering/entry[@name='Outbound-URL']
          /alert/member[text()='hacking']/../../@name

      # list looking for the Outbound-AV profile
      - name: av_outbound
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/virus/
          entry[@name='Outbound-AV']/@name
      # list with the dynamic classification action as reset-both
      - name: av_decoder_dynclass_resetboth
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/virus/
          entry[@name='Outbound-AV']/decoder/entry/mlav-action[text()='reset-both']/../@name
      # list with the dynamic classification action not reset-both
      - name: av_decoder_dynclass_not_resetboth
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/virus/
          entry[@name='Outbound-AV']/decoder/entry/@name
        filter_items: item not in av_decoder_dynclass_resetboth

      # check dynamic classification engine found in the configuration
      - name: av_engine_entries
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/virus/
          entry[@name='Outbound-AV']/mlav-engine-filebased-enabled/entry/@name
      # list with the dynamic classification engine action = enable
      - name: av_engine_dynclass_enable
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/virus/
          entry[@name='Outbound-AV']/mlav-engine-filebased-enabled/entry/mlav-policy-action[text()='enable']/../@name
      # list with the dynamic classification engine action != enable
      - name: av_engine_dynclass_not_enable
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/virus/
          entry[@name='Outbound-AV']/mlav-engine-filebased-enabled/entry/@name
        filter_items: item not in av_engine_dynclass_enable

      # use list to check for configuration of Recommended_Decryption_Profile
      - name: IS_decrypt_profile
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/decryption/
          entry[@name="Recommended_Decryption_Profile"]/@name
      # check max version in the recommended decrypt profile
      - name: profile_decryption_max_version
        capture_value: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/decryption/
          entry[@name="Recommended_Decryption_Profile"]/ssl-protocol-settings/max-version/text()

#-----------------
# tests

  - name: wf_realtime_update
    label: Wildfire dynamic update schedule set to real-time
    test: wf_update | tag_present('recurring.real-time')
    severity: medium
    fail_message: Wildfire should be configured to use real-time updates
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_master/viz_guide_panos.html#ironskillet-security-policies

  - name: url_dynclass
    label: URL Filtering Outbound dynamic classification set to block
    test: url_dynclass_not_block | length == 0 and 'Outbound-URL' in url_outbound and url_dynclass_entries | length
    severity: high
    fail_message: |
      {%- if 'Outbound-URL' not in url_outbound %}URL-filtering profile Outbound-URL not in configuration
      {%- elif url_dynclass_entries | length == 0 %}Dynamic classification options not found in configuration; may be unsupported version
      {%- else %}Dynamic classification for all options should be set to block; {{ url_dynclass_not_block }} not blocking
      {%- endif %}
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_master/viz_guide_panos.html#ironskillet-security-policies

  - name: url_hacking
    label: Outbound-URL hacking category moved from block to alert
    test: url_profiles_alert_hacking | length and 'Outbound-URL' in url_outbound
    fail_message: |
      {%- if 'Outbound-URL' not in url_outbound %}URL-filtering profile Outbound-URL not in configuration
      {%- else %}Hacking is set as alert in IronSkillet; No transfer of malicious content, only how to be malicious
      {%- endif %}
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_master/viz_guide_panos.html#ironskillet-security-policies

  - name: av_dynclass_decoder_action
    label: Outbound Dynamic Classification set to reset-both for all decoders
    test: av_decoder_dynclass_not_resetboth | length == 0 and 'Outbound-AV' in av_outbound
    severity: high
    fail_message: |
      {%- if 'Outbound-AV' not in av_outbound %}Antivirus profile Outbound-AV not in configuration
      {%- else %}Dynamic classification should be set to reset-both; {{ av_decoder_dynclass_not_resetboth}} set to another value
      {%- endif %}
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_master/viz_guide_panos.html#anti-spyware

  - name: av_dynclass_engines_action
    label: Outbound Dynamic Classification set to enable for all engines
    test: av_engine_dynclass_not_enable | length == 0 and 'Outbound-AV' in av_outbound and av_engine_entries | length
    severity: high
    fail_message: |
      {%- if 'Outbound-AV' not in av_outbound %}Antivirus profile Outbound-AV not in configuration
      {%- elif av_engine_entries | length == 0 %}No AV engine configuration found in configuration; may be unsupported version
      {%- else %}Dynamic classification should be set to enable for all engines; {{ av_engine_dynclass_not_enable }} set to another value
      {%- endif %}
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_master/viz_guide_panos.html#anti-spyware

  - name: decrypt_profile_tls13
    label: Recommended_Decryption_Profile protocol settings max version is TLS 1.3
    test: profile_decryption_max_version == 'tls1-3' and 'Recommended_Decryption_Profile' in IS_decrypt_profile
    severity: medium
    fail_message: |
      {%- if 'Recommended_Decryption_Profile' not in IS_decrypt_profile %}Recommended_Decryption_Profile not in configuration
      {%- elif profile_decryption_max_version | length == 0 %}The max version in the profile setting should be configured as v1.3
      {%- else %}The max version in the profile setting should be v1.3 instead of {{ profile_decryption_max_version }}
      {%- endif %}
    documentation_link: https://iron-skillet.readthedocs.io/en/docs_master/viz_guide_panos.html#url-filtering
